server:
  port: 8080

spring:
  profiles:
    active:  h2  # 기본 활성 프로필 설정
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
  
  # Message Source Configuration
  messages:
    basename: messages.messages
    encoding: UTF-8
    fallback-to-system-locale: false

# MyBatis Configuration
mybatis:
  type-aliases-package: io.goorm.mybatis_basic.model
  configuration:
    map-underscore-to-camel-case: true

# Logging Configuration
logging:
  level:
    root: INFO
    io.goorm.mybatis_basic: DEBUG
    io.goorm.mybatis_basic.controller: INFO
    io.goorm.mybatis_basic.service: DEBUG
    io.goorm.mybatis_basic.mapper: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    com.zaxxer.hikari: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"