spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/goorm_mybatis
    username: goorm-mybatis
    password: goorm1234
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    locations: classpath:db/migration/maria
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/maria/**/*.xml

logging:
  level:
    root: INFO
    io.goorm.mybatisboard: DEBUG
    io.goorm.mybatisboard.controller: INFO
    io.goorm.mybatisboard.service: DEBUG
    io.goorm.mybatisboard.mapper: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    com.zaxxer.hikari: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"